name: Build TEST

on:
  workflow_dispatch:

jobs:
  build:
    name: Build with ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
          - windows-2022
          - windows-2025
    
    steps:

      - name: Clone MPC-BE repository
        shell: pwsh
        run: |
          git clone --recursive https://github.com/Aleksoid1978/MPC-BE.git D:\\MPC-BE

      - name: Clone VideoRenderer repository
        shell: pwsh
        run: |
          git clone --recursive https://github.com/Aleksoid1978/VideoRenderer.git D:\\VideoRenderer

      - name: Set up MSYS
        shell: pwsh
        run: |
          curl -sSL https://raw.githubusercontent.com/Aleksoid1978/MSYS/refs/heads/main/MSYS_MinGW-w64_GCC_1421_x86-x64.7z -o MSYS_MinGW-w64_GCC_1421_x86-x64.7z
          7z x MSYS_MinGW-w64_GCC_1421_x86-x64.7z -oD:\\MSYS

      - name: Create environments.bat
        shell: pwsh
        run: |
          echo '@ECHO OFF' > D:\\MPC-BE\\environments.bat
          echo 'SET "MPCBE_MSYS=D:\\MSYS"' >> D:\\MPC-BE\\environments.bat
          echo 'SET "MPCBE_MINGW=D:\\MSYS\\mingw"' >> D:\\MPC-BE\\environments.bat

      - name: Execute update_gcc.bat
        shell: pwsh
        run: |
          cd D:\\MPC-BE
          .\\update_gcc.bat

      - name: Install InnoSetup - windows-2025
        if: matrix.os == 'windows-2025'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://jrsoftware.org/download.php/is.exe -OutFile D:\\is.exe
          Start-Process -FilePath D:\\is.exe -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-" -Wait

      - name: Build VideoRenderer
        shell: pwsh
        run: |
          cd D:\\VideoRenderer
          .\\build_mpcvr.cmd NoWait

      - name: Build MPC-BE
        shell: pwsh
        run: |
          cd D:\\MPC-BE
          .\\build.bat Clean All NoWait
          .\\build.bat Build All Packages NoWait

      - name: Upload MPC-BE logs to artifact
        uses: actions/upload-artifact@main
        with:
          name: "MPC-BE.LOGS-${{ matrix.os }}"
          path: D:/MPC-BE/_bin/logs/

      - name: Upload VideoRenderer logs to artifact
        uses: actions/upload-artifact@main
        with:
          name: "MPC-VideoRenderer.LOGS-${{ matrix.os }}"
          path: D:/VideoRenderer/_bin/logs/

      - name: Upload MPC-BE bin to artifact
        uses: actions/upload-artifact@main
        with:
          name: "MPC-BE.BIN-${{ matrix.os }}"
          path: D:/MPC-BE/_bin/Packages/**/*.*

      - name: Upload VideoRenderer bin to artifact
        uses: actions/upload-artifact@main
        with:
          name: "MPC-VideoRenderer.BIN-${{ matrix.os }}"
          path: D:/VideoRenderer/_bin/MpcVideoRenderer*.zip
